### ISSUE TITLE
JOSM 14260 nenatiahne plugin

### ISSUE THREAD

**Issue by kaylesk** [FreemapSlovakia/freemapKaPor#12]
Pre info (možno to bude problém JOSM) 
JOSM 14260 (latest) hádže chybu a nespustí plugin. V JOSM 14178 (tested) ide. Mal som ale staršiu latest v ktorej to išlo, len neviem číslo.
Asi to bude niečo podobné ako s Mapillary - https://josm.openstreetmap.de/ticket/16737 tiež nejde po update JOSM

```
2018-09-19 15:37:08.186 INFO: nahr�vanie pluginu 'freemapkapor' (verzia 54)
2018-09-19 15:37:08.189 SEVERE: org.openstreetmap.josm.plugins.PluginException: Nastala chyba v plugine freemapkapor. Pr��ina: java.lang.reflect.InvocationTargetException. Pr��ina: java.lang.NoClassDefFoundError: org/openstreetmap/josm/Main. Pr��ina: java.lang.ClassNotFoundException: org.openstreetmap.josm.Main
org.openstreetmap.josm.plugins.PluginException: Nastala chyba v plugine freemapkapor
        at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:355)
        at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:766)
        at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:850)
        at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:889)
        at org.openstreetmap.josm.gui.MainApplication.loadLatePlugins(MainApplication.java:1147)
        at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:913)
        at org.openstreetmap.josm.gui.MainApplication$3.processArguments(MainApplication.java:283)
        at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:710)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:350)
        ... 7 more
Caused by: java.lang.NoClassDefFoundError: org/openstreetmap/josm/Main
        at sk.freemap.kapor.KaporPlugin.<init>(KaporPlugin.java:24)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: org.openstreetmap.josm.Main
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.openstreetmap.josm.plugins.PluginClassLoader.loadClass(PluginClassLoader.java:73)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 13 more
```

**Comment by zdila** [comment]
asi uz to je fixnute
