### ISSUE TITLE
Plugin nefunguje v aktualnom JOSM 18583

### ISSUE THREAD

**Issue by viliam-durina** [FreemapSlovakia/freemapKaPor#16]
Chyba:
```
org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin freemapkapor. Cause: java.lang.reflect.InvocationTargetException. Cause: java.lang.NoSuchMethodError: 'void org.ejml.dense.row.CommonOps_DDRM.mult(org.ejml.data.DMatrix1Row, org.ejml.data.DMatrix1Row, org.ejml.data.DMatrix1Row)'
org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin freemapkapor
	at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:387)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:813)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:898)
	at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:950)
	at org.openstreetmap.josm.gui.MainApplication.loadLatePlugins(MainApplication.java:1232)
	at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:962)
	at org.openstreetmap.josm.gui.MainApplication$3.processArguments(MainApplication.java:277)
	at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:742)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:382)
	... 7 more
Caused by: java.lang.NoSuchMethodError: 'void org.ejml.dense.row.CommonOps_DDRM.mult(org.ejml.data.DMatrix1Row, org.ejml.data.DMatrix1Row, org.ejml.data.DMatrix1Row)'
	at org.geotools.referencing.operation.matrix.GeneralMatrix.mul(GeneralMatrix.java:885)
	at org.geotools.referencing.operation.matrix.GeneralMatrix.multiply(GeneralMatrix.java:646)
	at org.geotools.referencing.operation.DefaultCoordinateOperationFactory.createOperationStep(DefaultCoordinateOperationFactory.java:1235)
	at org.geotools.referencing.operation.DefaultCoordinateOperationFactory.createOperationStep(DefaultCoordinateOperationFactory.java:1282)
	at org.geotools.referencing.operation.DefaultCoordinateOperationFactory.createOperationStep(DefaultCoordinateOperationFactory.java:925)
	at org.geotools.referencing.operation.DefaultCoordinateOperationFactory.findOperationSteps(DefaultCoordinateOperationFactory.java:1146)
	at org.geotools.referencing.operation.DefaultCoordinateOperationFactory.findOperations(DefaultCoordinateOperationFactory.java:347)
	at org.geotools.referencing.operation.DefaultCoordinateOperationFactory.createOperation(DefaultCoordinateOperationFactory.java:207)
	at org.geotools.referencing.operation.BufferedCoordinateOperationFactory.createOperation(BufferedCoordinateOperationFactory.java:232)
	at org.geotools.referencing.CRS.findMathTransform(CRS.java:1354)
	at sk.freemap.kapor.Projection.initCRS(Unknown Source)
	at sk.freemap.kapor.KaporPlugin.<init>(Unknown Source)
	... 13 more
```

Je plugin stale podporovany? V pripade tipu na pricinu chyby by som to mozno dokazal opravit.

**Comment by jose1711** [comment]
Nefunguje myslim od maja tohto roku. A vratit sa uz nevrati.

**Comment by zdila** [comment]
kapor je mrtvy. archivujem repozitar.
